# Generated by Django 6.0.5 on 2026-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_newsanalysis_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(db_index=True, max_length=1000)),
                ('article_text', models.TextField(blank=True, default='')),
                ('label', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
