# Generated by Django 6.0.5 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_knownarticle_newsanalysis_confidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsanalysis',
            name='matched_keywords',
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newsanalysis',
            name='article_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
