# Generated by Django 6.0.5 on 2026-08-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_remove_newsanalysis_matched_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownarticle',
            name='headline_key',
            field=models.CharField(db_index=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='knownarticle',
            name='label_basis',
            field=models.CharField(choices=[('fact_check', 'Verified by a fact-checker'), ('source', 'Inferred from the publisher')], default='source', max_length=20),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='matched_extract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newsanalysis',
            name='matched_headline',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='knownarticle',
            name='headline',
            field=models.CharField(max_length=1000),
        ),
        migrations.AddIndex(
            model_name='knownarticle',
            index=models.Index(fields=['headline_key', 'label_basis'], name='knownarticle_lookup_idx'),
        ),
    ]
