# Generated by Django 6.0.5 on 2026-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_knownarticle_headline_key_knownarticle_label_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsanalysis',
            name='web_check',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
